# Reference
# 1. https://github.com/ichantzaras/creamcrackerz
# 2. https://github.com/ichantzaras/creamcrackerz/blob/master/ic.py
# 3. https://gist.github.com/Will-Banksy/f4a5ea554b8e90e2c458c4106533f829
def calculate_ic(text):
    """
    Calculate the Index of Coincidence (IC) for a given text.
    
    Parameters:
        text (str): The text for which to calculate the IC.
        
    Returns:
        float: The calculated IC value.
    """
    # Initialize a dictionary to hold the frequency of each letter
    frequency_dict = {}
    
    # Calculate the frequency of each letter in the text
    for letter in text:
        if letter in frequency_dict:
            frequency_dict[letter] += 1
        else:
            frequency_dict[letter] = 1
    
    # Calculate the IC
    N = len(text)
    ic = 0
    
    # Calculate the sum of (freq * (freq - 1)) for each letter frequency
    for freq in frequency_dict.values():
        ic += (freq * (freq - 1))
    
    # Normalize the IC by dividing by (N * (N - 1))
    ic /= (N * (N - 1))
    
    return round(ic, 3)

#For key length 2
len2 = ["FKJSAUTJLMFKKWAXGUNAKNEWMAKHHUXJFULZEJOOMUTOEDZANBAKPATTGNSVOCULIEGRTXUZGGGRTQSVTXITQQZQBBQBUHXXKIIBMCTHEXIGDWETCRKEGTAMRUOTQIKAUMQGGOKMYGOTPUYSMMKDSMETQRMPANUADSPEGGLGPTKAKHQELJLWEKMPMUJQIDEHGRJAXQEVEXGHWKAEN",
    "HOAZFDBQVKHZFGCWGMGVSWWNPNWFKIIMEJGLBDAJDWKAGEZUMQPVQXAELQYKKIMCAHXKUQNVIXHILDOVEQTJTCQZAREMFKQTZQYYSWFZQOSPUTALFOMTQOYKYCQNOHVACTLBRXNSPIAFRXMZRPZMQVOGGNCPTDMHOCPXQRMFKVOEFHVOKMQTNIGHJNGGTKITSGAUVEGFCMOMVOZAQ"]

#For key length 3
len3 = ["FOSFTQMHKGXGNVNWMNHKXMUGEDODTADZNQKQTENYOILAGKXNGXRLSVXTQCQAQMHQKQBSTZXSDTTFKTTYRCTOKAMLGXMPOFUMMPDQEGRCADAOPXGMPVAFQOJQEIPJJGDIGGAVEFXOWOEQ",
    "HJZUBLKKFAWUGKWWPKFUIFJZBOJUKEEAMAVAAGQVKUCEXTQZIGIQOTQTTZZBEUKXZIYCFEOGUELRMGOMYONIVUTGRKSGAPXSRKMMOQNPTUHSPGRGKKEHVLMWNMHUGIKHSJUQGEMHVAA",
    "KAADJVFZWCGMASENAWHIJELLJAMWOGZUBPPXTLSKCMIHRUUVGHTDVEIJQQBRBFXTIYMWHQIPWACOEQAKUQQHACQBONYITRYZMZSVTGMPNMDCEQLFTOKHEKLTKGMNQTETRAXEVCGMKZN"]

#For key length 4
len4 = ["FJATLFKAGNKEMKHXFLEOMTEZNAPTGSOUIGTUGGTSTIQZBQUXKIMTEIDECKGAROQKUQGKYOPYMKSEQMAUDPGLPKKQLLEMMJIEGJXEEGWAN",
    "HAFBVHFCGGSWPWKIEGBADKGZMPQALYKMAXUNIHLOETTQAEFQZYSFQSUAFMQYYQOVCLRNPARMRZQOGCTMOPQMKOFVKQNGJGTISAVGCOVZQ",
    "KSUJMKWXUANWAHUJUZJOUODABKATNVCLERXZGRQVXTQQBBHXIBCHXGWTRETMUTIAMGOMGTUSMDMTRPNASEGGTAHEJWKPUQDHRAQVXHKE",
    "OZDQKZGWMVWNNFIMJLDJWAEUQVXEQKICHKQVXIDVQJCZRMKTQYWZOPTLOTOKCNHATBXSIFXZPMVGNPDHCXRFVEHOMTIHNGKTGUEFMMOA"]

#For key length 5
len5 = ["FAUQFFXMKWAFXEZDMKDUAQTQOMEKUIRDTTQZQFXQMFXPEFEORQIAQRMIPMMMEGPDDPGFKFEMEGUGESAEEOKA",
"HSDLHWWNSWNHIULODOENPAESKLHTNGISETCBEHTISHODARTAYTHULOSORSPSORPUOERPOHOLNPNIIRUECHON",
"KZTVKGGGNNKKJJEAUAZMKXGYCCGUZXTOXJZABKKYCZIUTOGYUNKCGXYAUZKQTNAMSXLKAHLQKHJTHGXGXMAQ",
"OABMZAGAWMWUMLBOWEZBVTLVIIXXVGLVQQQBMXZBWESWLKQMCQVMBKPTXMZMGMTACGMTEQKWIMGDTJVVMWZ",
"JFJKKCUVEPHIFGJJTGAQPANKUARQGHQVITQRUQIYTQGTCMTKOOATGNGFYRDVQCNHPQGVKVJTMJQKGAQFGVE"]

#For key length 6
len6 = ["FSTMKXNNMHXUEOTDNKTNOLGXGRSXQQQHKBTXDTKTRTKMGMOUMDERAAPGPAQJEPJDGAEXWE",
    "HZBKFWGWPFIJBJKEMVAQKCXQIIOQTZEKZYFOULMOYNVTRSAXRMONTHPRKEVMNHGKSUGMVA",
    "KAJFWGAEAHJLJMOZBPTSCIRUGTVIQBBXIMHIWCEAUQAQOYTYMSTMNDELTKELKMQERXVGKN",
    "OFQHGGVWNKMGDDAZQQEYIAKNXLVTCAMQQSZSTFTYCOALXPFMPQGCDOXMVFOQIJGIGVFOOQ",
    "JULKAUKWKUFZOUEAAAGVUETZGQTTZBUXICEGERGMOIUGKGPSKMQPUSGGKHLWMUIHJQEHA",
    "ADVZCMSNWIELAWGUPXLKMHUVHDEJQRFTYWQPAOQKQHCBNIRZZVGPMCQFOHKTGNTTAECMZ"]

#For key length 7
len7 = ["FZJHAMNPHMZATEBQGKLXUXQEQZBQIWXUCTMQKTOPPZDOMDSQPEEQMNDSXFHZ",
    "HAQKCNWAKFLOKZQALOCRNGDXTBMXYTOWFGKTVQXGRMMTCUCGKKOWGJKRVEME",
    "KFLZXGENUEEJOZAXNKIKZHSQQAUTBFITRQRNALKIURSGPMPRTFLTPGEGQCWA",
    "OUVKWAWKIUBMAAPTQCATVROICBFKYHSEOTYQAGNOXMQQPAPLVHKEHQIJEXVN",
    "JDMFGVWWXJJDEUKASIEUGIVTZRHZMZGAKOUOUBMAYPMGAHEMKHJNMGHAEMKQ",
    "ATKWGKNHILDUGNVTYUHXITVTQQKISEPTMACICGSTMKVRTDXGOQMKJITAGGO",
    "SBFGUSMFJGOWDMPEVMGQGLTJQEXQCQDLEYOHMRYFSZENNOGFAVLIUTGUVOA"]

#For key length 8
len8 = ["FALKGKMHFEMENPGOITGTTQBUKMEDCGRQUGYPMSQADGPKLEMIGXEWN",
    "HFVFGSPKEBDGMQLKAUILETAFZSQUFQYOCRPRRQGTOQKFKNJTSVCVQ",
    "KUMWUNAUUJUDBANCEXGQXQBHICXWRTUIMOGUMMRNSGTHJKUDRQXK",
    "ODKGMWNIJDWEQXQIHQXDQCRKQWOTOOCHTXIXPVNDCRVHMINKGEMO",
    "JTFANEKXLOTZATSUGUGSIZQXITIEKAOKQKOYKEMUPLKQLMJEJEGA",
    "ABHCGWWIGAKZPAYMXNHOTQEQYFSAMYQVLNAMZOCMPMOVQGGIAGOZ",
    "SJKXAWHJZOOAKTVLRZRVTQBXBHGTEMTAGMTSDTPAEGAEWPQHAVHE",
    "ZQZWVNFMLJAUVEKCKVIVJZMTYZPLTKNABSFZMGPHXFEOTHGTUFMA"]

#For key length 9
len9 = ["FFMGNWHMEDDQTYLKGLXCQQBZDFTCKLMFMQRDPMAOEJDGEOE",
    "HUKAGWFFBUEAAVCTIQQZEXYEUROOVGSPRMNUPGELNUKJGHA",
    "KDFCANHEJWZPTKIUGDIQBTMQWOAQABYRMVMMEFKKKNEAVMN",
    "OTHXVMKUDTZKEOAXXSTQMKSXTKYTAGPUPECAXPFJIJIAFWQ",
    "JBKWKPUJOKAVGKEQGOTZUZCOEMMNURGXKOPHGKHMMGHUEV",
    "AJZGSAILAOUPLCHUHVJBFIWIAEKQCOIYZTPDQTHLGQTXCK",
    "SQKGNNXGOANQNIGNRVQAHQTSTTROMXOMDGAOGVQQPGGVXO",
    "ZLFUWKIZJEMAQUXZITTBKIFGLGYITKASMQTSRKVWHISQMA",
    "AVWMEWJLMGBXSMRVTEQRXYHPCQUHQNTZSGNCLOETMTREGZ"]

#For key length 10
len10 = ["FUFXKAXZMDATOEURTQQXMXEERIQMPMEPDGKEEUEAEK",
    "HDHWSNILDEPEKHNIECETSOATYHLSRPOPOROONNIUCO",
    "KTKGNKJEUZKGCGZTXZBKCITGUKGYUKTASLALKJHXXA",
    "OBZGWWMBWZVLIXVLQQMZWSLQCVBPXZGTCMEKIGTVMZ",
    "JJKUEHFJTAPNURGQIQUITGCTOAGGYDQNPGKJMQGQGE",
    "AQFMWFEDKUQQMKIDTZFQFPFOQARIMMGDPFFMGGSEOA",
    "SLWNWHUOONASLTGSTBHIHDRATUOOSSRUEPHLPIREHN",
    "ZVGGNKJAAMXYCUXOJAKYZUOYNCXAZQNMXKHQHTGGMQ",
    "AMAAMULOEBTVIXGVQBXBEWKMQMKTMMMAGTQWMDJVW"]

keys = [len2, len3, len4, len5, len6, len7, len8, len9, len10]

for key in range(len(keys)):
    key_set = keys[key]
    print('\n')
    for y in range(len(key_set)):
        print(f"IC for key length {key+2} Y{y}:", calculate_ic(key_set[y]))